# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ABOUT THE THING YOU'RE LOOKING AT
email: emmangelos666@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site was started as a web design portfolio, 
  but may develop into something worse. Like a 
  series of bad vignettes about eating macaroni and
  cheese in a thunderstorm. 
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://emmangelos.de" # the base hostname & protocol for your site
twitter_username: what  
github_username:  emmangelos

# Build settings
markdown: kramdown

theme: jekyll-theme-architect
